version: "3.9"

services:

  # Reverse proxy
  nginx:
    platform: linux/amd64
    image: nginx
    container_name: local_nginx
    volumes:
      - ./reverse_proxy.conf:/etc/nginx/nginx.conf
    ports:
      - "8080:8080"

  # Databases
  sql-injection-db:
    image: mysql/mysql-server:8.0.25
    container_name: sql-injection-db
    healthcheck:
      test: [ "CMD", "mysqladmin" ,"ping", "-h", "localhost" ]
      timeout: 45s
      interval: 2s
      retries: 30
    env_file:
      - env/sql-injection.env
    ports:
      - "3306"
        
# Java services
  sql-injection-service:
    build:
      context: ./sql-injection
      dockerfile: Dockerfile
    restart: always
    ports:
      - "8080"
    depends_on:
      sql-injection-db:
        condition: service_healthy
    container_name: sql-injection-service
    environment:
      MYSQL_HOST: sql-injection-db
    env_file:
      - env/sql-injection.env

